title: The Hiking Hub
author: Blair Preston
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Are you new to the great state of Kentucky? Or have you been here a while and
  are looking to spice up your adventures? You've come to the right place! 
  Insider scoop to the best hiking spots in the state!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
